### PR TITLE
Fix RETURN selector

### PR DESCRIPTION
**Pull request by Lassebq**
Properly match return when it's the last instruction in the method

### CODE REVIEW

**Comment by Geolykt** [comment]
Well, I'm not exactly sure why this isn't an issue with other injectors since they use similar logic - I suppose not really of relevance since they cannot match returns.
Also, I haven't tested with slices so far. I anticipate this PR might change some behavior on that front, but it's unlikely you'd want to match the last instruction of a slice anyways since the `At` was already programmed for that.

**Comment by Lassebq** [comment]
I imagine there are issues with other injectors, its just an edge case because return is more likely to be the last instruction. Instructions anywhere within body work as intended

**Comment by Lassebq** [comment]
I think its best to getSelected from SlicedInjectionPointSelector instead of instruction after it. That way you can still target last instruction when the bounds are set explicitly

**Comment by Geolykt** [comment]
that makes sense. I'll keep that in the back of my mind - hopefully.

**Pull request merged**
